### ISSUE TITLE
Connection to ModernAgile.org is Not Secure

### ISSUE THREAD

**Issue by msolomonTMG** [modernagile/modernagile.github.io#9]
The modern agile site is served over HTTP, not HTTPS.
![screen shot 2018-08-08 at 11 13 09 am](https://user-images.githubusercontent.com/8402278/43846331-10dc86b0-9afc-11e8-8412-03df93ac4141.png)

Github sites now offer HTTPS for no additional cost. To set this up, someone who owns the modernagile.org domain and admin rights for this repo can:

- Go to "Settings" in this repo and click "Enforce HTTPS" as described in these steps: https://help.github.com/articles/securing-your-github-pages-site-with-https/  
- Change the IP addresses for the modernagile.org A records to: 185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153 as described in these steps: https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by cecilgwilliams** [comment]
This has been done!
